development:
  database: disaster_information
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: disaster_information_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db